CNDE-2911-liquibase-cdc: RTR Liquibase Helm Adding script to enable the Change Data Capture in ODSE

diff --git a/charts/liquibase/templates/job.yaml b/charts/liquibase/templates/job.yaml
--- a/charts/liquibase/templates/job.yaml
+++ b/charts/liquibase/templates/job.yaml
@@ -82,6 +82,18 @@ spec:
                 [ $status -eq 0 ]  || exit 1
               fi
 
+              # ODSE Admin Tasks
+              echo "Checking ODSE Admin Tasks  enabled flag {{ .Values.enabled_databases.odseAdminTasks }} in DB : {{ .Values.jdbc.odse_db_url }}"
+              if [ {{ lower .Values.enabled_databases.odseAdminTasks }} == "enabled" ]; then
+                echo "Executing changelog {{ .Values.changelog.odseAdminTasks }} in DB : {{ .Values.jdbc.odse_db_url }}"
+                liquibase --changelog-file="{{ .Values.changelog.odseAdminTasks }}" --searchPath="./" --url="{{ .Values.jdbc.odse_db_url }}" --username={{ .Values.jdbc.username }} --password={{ .Values.jdbc.password }} update
+                # Returns non-zero code if failed
+                status=$?
+                ## Log and exit if failed
+                [ $status -eq 0 ] && echo "{{ .Values.changelog.odseAdminTasks }} scripts : execution success!" || echo "ERROR: {{ .Values.changelog.odseAdminTasks }} failed with exit code $status"
+                [ $status -eq 0 ]  || exit 1
+              fi
+
               echo "Liquibase Update Complete. All scripts: execution success! Exiting"
 {{/*              echo "Sleep infinitely"*/}}
 {{/*              sleep infinity*/}}
