Cnat 507 promote rtr (#1197)
* CNAT-507: Adding the RTR java services values files for the int1 and test environments

* CNAT-507: Adding the RTR java services values files for the int1 and test environments

* CNAT-507: Adding the RTR java services values files for the int1 and test environments

* CNAT-507: Updating the RTR debezium snapshot mode to no_data for all connectors

* CNAT-507: Updating the RTR debezium configs and the RTR java services tags updated

* CNAT-507: Updating the RTR debezium configs

* CNAT-507: Updating the RTR debezium configs

* update debezium config

diff --git a/charts/debezium/templates/deployment.yaml b/charts/debezium/templates/deployment.yaml
--- a/charts/debezium/templates/deployment.yaml
+++ b/charts/debezium/templates/deployment.yaml
@@ -88,23 +88,23 @@ spec:
                     done
 
                     #4. Starting SRTE task if enabled
-                    if [ {{ lower .Values.connect.connector_enable.nbs_srte }} == "enabled" ]; then
-                    echo "Starting SRTE task with config: $(cat /etc/debezium/connector-srte.json)"
-                    curl --request POST \
+                    if [ "{{ lower .Values.connect.connector_enable.nbs_srte }}" == "enabled" ]; then
+                      echo "Starting SRTE task with SRTE configuration"
+                      curl --request POST \
                       --header "Accept:application/json" \
                       --header "Content-Type:application/json" \
                       --data '@/etc/debezium/connector-srte.json' \
-                      "http://127.0.0.1:8083/connectors/";
+                      "http://127.0.0.1:8083/connectors/" || echo "Failed to start SRTE connector";
                     fi
 
                     #5. Starting ODSE task if enabled
-                    if [ {{ lower .Values.connect.connector_enable.nbs_odse }} == "enabled" ]; then
-                    echo "Starting ODSE task with config: $(cat /etc/debezium/connector-odse.json)"
-                    curl --request POST \
+                    if [ "{{ lower .Values.connect.connector_enable.nbs_odse }}" == "enabled" ]; then
+                      echo "Starting ODSE task with ODSE configuration"
+                      curl --request POST \
                       --header "Accept:application/json" \
                       --header "Content-Type:application/json" \
                       --data '@/etc/debezium/connector-odse.json' \
-                      "http://127.0.0.1:8083/connectors/";
+                      "http://127.0.0.1:8083/connectors/" || echo "Failed to start ODSE connector";
                     fi
 
                     connectors=($(curl --request GET  "http://127.0.0.1:8083/connectors"))
